language: java

jdk:
  - oraclejdk8

before_install:
  - export UMPLE_DIR=~/umple/Umple
  - git clone --depth=2 --branch=master https://github.com/umple/Umple.git $UMPLE_DIR
  
before_script:
  # build
  - cd $UMPLE_DIR/build/
  - ant -Dmyenv=local -f build.umple.xml first-build
  - ant -Dmyenv=local -f build.umple.xml umpleSelf compile packageMainJar # ignore tests, we don't care about them 

script:
  - cd $TRAVIS_BUILD_DIR
  - ant -f build.xml -Dumple.core.jar=$UMPLE_DIR/dist/umple.jar compile
  - ant -f build.xml -Dumple.core.jar=$UMPLE_DIR/dist/umple.jar test

os:
  - linux
