language: java

jdk:
  - oraclejdk8

before_install:
  - wget https://github.com/umple/Umple/raw/master/lib/umple.jar -O ./umple.jar
  - export UMPLE_JAR=`pwd`"/umple.jar"


script:
  - ant -f build.xml -Dumple.core.jar=$UMPLE_JAR compile
  - ant -f build.xml test

os:
  - linux
